export const companiesMock = [
    'test1',
    'test2',
    'test3',
    'Aa-Dee Machinefabriek en Staalbouw Nederland B.V.',
    'AAE Advanced Automated Equipment B.V.',
    '@EasePay B.V.',
    '@Fentures B.V.',
    '01-10 Architecten B.V.',
    '050media',
    '073 Meeting Company B.V.',
    '100 Grams B.V.',
    '10X Genomics B.V.',
    '12Build Sales B.V.',
    '180 Amsterdam BV',
    '2 Getthere B.V.',
    '2 Getthere Holding B.V.',
    '20Face B.V.',
    '21 Markets B.V.',
    '21SanSec B.V.',
    '247HAIR',
    '247TailorSteel B.V.',
    '24sessions.com B.V.',
    '2525 Ventures B.V.',
    '2-B Energy Holding',
    '2Care4Kids Holding B.V.',
    '2M Engineering Limited',
    '360KAS B.V.',
    '361° Europe B.V.',
    '365Werk Contracting B.V.',
    '3BFAB B.V.',
  ];